CREATE TABLE value_set (id VARCHAR(250) NOT NULL , version VARCHAR(100) NOT NULL , PRIMARY KEY (id));

CREATE TABLE value_set_value (id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),valueSetId VARCHAR(250) NOT NULL ,code VARCHAR(250) NOT NULL ,system VARCHAR(250) NOT NULL ,PRIMARY KEY (id));
